# Generated by Django 3.2.25 on 2026-01-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='assessments/')),
                ('ground_truth_labels', models.JSONField()),
                ('difficulty', models.CharField(default='easy', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_boxes', models.JSONField()),
                ('iou_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derma.assessmentimage')),
            ],
        ),
    ]
