# Generated by Django 3.2.25 on 2026-01-08 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('derma', '0002_userattempt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentimage',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='userattempt',
            name='created_at',
        ),
        migrations.AddField(
            model_name='assessmentimage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='assessmentimage',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modified date'),
        ),
        migrations.AddField(
            model_name='assessmentimage',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted date'),
        ),
        migrations.AddField(
            model_name='assessmentimage',
            name='diagnosis_class',
            field=models.CharField(blank=True, help_text='e.g. Acne, Rosacea, Melanoma', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessmentimage',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentimage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='assessmentimage',
            name='metadata',
            field=models.JSONField(default=dict, help_text="e.g. {'lighting': 'poor', 'zoom': '10x'}"),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modified date'),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted date'),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='detailed_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='time_taken_seconds',
            field=models.FloatField(blank=True, help_text='Reaction time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='user_classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentimage',
            name='ground_truth_labels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentimage',
            name='image_file',
            field=versatileimagefield.fields.VersatileImageField(upload_to='assessments/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='userattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derma_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userattempt',
            name='user_boxes',
            field=models.JSONField(blank=True, help_text="Student's drawn coordinates", null=True),
        ),
    ]
